# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs
export JAVA_HOME=/home/osboxes/products/jdk/jdk_latest
export PATH=$JAVA_HOME/bin:$PATH
